version: '3.3'

services:
    nginx:
        image: nginx:1.17.7
        ports:
            - "80:80"
            - "443:443"
            - "8099:8099"
        volumes:
            - "/etc/localtime:/etc/localtime:ro"
            - "./nginx.conf:/etc/nginx/conf.d/default.conf:ro"
            - "./certs:/certs:ro"