version: '3.3'

services:
    ubuntu:
        image: nginx.ssl2
        ports:
            - "0.0.0.0:80:80"
            - "0.0.0.0:443:443"
            - "0.0.0.0:8099:8099"
        volumes:
            - "/etc/localtime:/etc/localtime:ro"
            - "./nginx.conf:/etc/nginx/nginx.conf:ro"
            - "./certs:/certs:ro"
        command:
            ["yes"]
            # ["nginx","-g","daemon off;"]